version: '3'
services:
  database:
    image: mongo:latest
    container_name: ct_mongo
    hostname: mongo-db
    restart: always
    # env_file:
    #   - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
    ports:
      - 17027:27017
    command: ['-f', '/etc/mongod.conf']
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
      - ./scripts/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./data/db:/data/db:rw
      - ./data/log:/var/log/mongodb:rw

  mongoclient:
    image: mongoclient/mongoclient
    container_name: ct_mongoclient
    restart: unless-stopped
    ports:
      - 3000:3000
    links:
      - database:mongo-db
